services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_dev
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: botcasts_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: